extends Node

var MIN_HEIGHT = -127
var MAX_HEIGHT = 128
var DEEP_OCEAN_FLOOR = -127
var OCEAN_FLOOR = -64
var RIVER_FLOOR = -10
var BEACH_FLOOR = 0
var HILL_FLOOR = 21
var MOUNTAINS_FLOOR = 42
var MOUNTAINS_PEAK = 118
